print("===== STUDENT REGISTRATION SYSTEM =====")

name = input("Enter your name: ")
age = input("Enter your age: ")
department = input("Enter your department: ")
email = input("Enter your email: ")
phone_number = input("Enter your phone number: ")
school = input("Enter your school: ")

print("\n===== STUDENT REGISTRATION =====")
print("Welcome", name)
print("You have successfully registered.")
print()
print("Name:", name)
print("Age:", age)
print("Department:", department)
print("Email:", email)
print("Phone Number:", phone_number)
print("School:", school)
